import { createToolPolicy } from "./tool-policy.mjs";

export const OPERATOR_CONTEXT_MARKER = "<!-- generated by pca: operator context -->";
export const OPERATOR_CONTEXT_DOCS_URL = "https://www.shawntabrizi.com/polkadot-chat-agents/";
export const PERSONA_TEMPLATE = `# Bot persona

<!--
Describe the operator-owned personality here. This file is never overwritten by pca.

Name or role:
Who this bot is for:
Tone:
Priorities or boundaries:
-->
`;

const modelPolicyText = (modelPolicy) => {
  if (modelPolicy == null) return "open";
  if (Array.isArray(modelPolicy) && modelPolicy.length > 0) {
    return `restricted to ${modelPolicy.join(", ")}`;
  }
  return "locked by the operator";
};

const commandText = (commands) => (commands ?? [])
  .filter((entry) => typeof entry?.command === "string" && typeof entry?.meaning === "string")
  .map(({ command, meaning }) => `${command}—${meaning}`)
  .join("; ");

// Pure runtime facts for a model. Persona belongs in PERSONA.md and is kept
// separate by agent-runtime; this block is deterministic over its arguments.
export const buildOperatorContext = ({
  username,
  transport,
  policy,
  model,
  modelPolicy,
  commands,
  docsUrl = OPERATOR_CONTEXT_DOCS_URL,
} = {}) => {
  const normalizedPolicy = createToolPolicy(policy);
  const tools = normalizedPolicy.capabilities;
  const botName = String(username ?? "").trim() || "this bot";
  const transportName = String(transport ?? "").trim() || "polkadot-app";
  const activeModel = String(model ?? "").trim() || "engine default";
  const lines = [
    `You are \`${botName}\`, a chat bot that people message from the Polkadot app (transport: ${transportName}). You run under polkadot-chat-agents (\`pca\`).`,
    tools.length
      ? `Tools: ${tools.join(", ")} (scope: ${normalizedPolicy.scope}). Never emit tool-call markup.`
      : "Tools: no tools. Never emit tool-call markup. If a request needs a tool, say tools are disabled and the operator can enable them.",
    "Operator tool command: `pca run|deploy <bot> --allowed-tools read,write,bash,web,subagents|all --tool-scope workspace|container`.",
    `Model: ${activeModel}; /model switching is ${modelPolicyText(modelPolicy)}. Operator command: \`pca model <bot>\`.`,
    `Chat commands: ${commandText(commands) || "none"}.`,
  ];
  if (tools.includes("read")) lines.push("Attachments: incoming files are staged in a per-turn attachment directory.");
  if (tools.includes("write")) lines.push("Generated files placed in the per-turn output directory are sent back.");
  lines.push(
    "Replies are read on a phone: keep them short and use no Markdown tables. The transport adds the status receipt; do not write one.",
    `Docs: ${docsUrl}`,
  );
  return lines.join("\n");
};
