import { createToolPolicy } from "./tool-policy.mjs";

export const OPERATOR_CONTEXT_MARKER = "<!-- generated by pca: operator context -->";
export const OPERATOR_CONTEXT_DOCS_URL = "https://www.shawntabrizi.com/polkadot-chat-agents/";
export const PERSONA_TEMPLATE = `# Bot persona

<!--
Describe the operator-owned personality here. This file is never overwritten by pca.

Name or role:
Who this bot is for:
Tone:
Priorities or boundaries:
-->
`;

// Spec 0006; the block format is parsed by lib/buttons-block.mjs.
export const BUTTONS_HINT = "Buttons: the chat app renders a trailing fenced ```buttons block in your reply as real clickable buttons. "
  + "When the user asks for buttons, or should pick from a few choices, you MUST end the reply with exactly one block holding JSON "
  + "{\"rows\":[[{\"label\":\"Yes\",\"action\":{\"command\":\"yes\"}}]],\"oneShot\":false}; "
  + "an action is {\"command\":text sent back to you as the user's next message}, {\"callback\":string echoed back to you as \"[button] <label> (payload: <hex>)\"} "
  + "or {\"url\":\"https://...\"}; at most 8 rows of 4 buttons, labels up to 40 characters; put nothing after the block. "
  + "Labels are at most 40 characters: a few words, never a sentence; put the full text of an answer in the message and use short labels like A, B, C or the key words. "
  + "Exact form, no other: a line ```buttons (not ``` or ```json), then the {\"rows\":[[...]]} object (never a bare array), then a line ```, and the reply ends there.";

// Spec 0009: one line when the turn comes from a group room. The message
// itself arrives as "[group <name>] <sender>: <text>". In v1 a bot SHOULD NOT
// send tx buttons (spec 0007 intents) in a group (M12c ruling).
export const groupHint = ({ name, size }) =>
  `You are in the group ${name} with ${size} people; address the sender by name. Do not send tx (transaction) buttons in a group.`;

const modelPolicyText = (modelPolicy) => {
  if (modelPolicy == null) return "open";
  if (Array.isArray(modelPolicy) && modelPolicy.length > 0) {
    return `restricted to ${modelPolicy.join(", ")}`;
  }
  return "locked by the operator";
};

const commandText = (commands) => (commands ?? [])
  .filter((entry) => typeof entry?.command === "string" && typeof entry?.meaning === "string")
  .map(({ command, meaning }) => `${command}—${meaning}`)
  .join("; ");

// Pure runtime facts for a model. Persona belongs in PERSONA.md and is kept
// separate by agent-runtime; this block is deterministic over its arguments.
export const buildOperatorContext = ({
  username,
  transport,
  policy,
  model,
  modelPolicy,
  commands,
  buttons = false, // spec 0006: this peer can render a buttons message
  group = null, // spec 0009: { name, size } when the turn comes from a group
  docsUrl = OPERATOR_CONTEXT_DOCS_URL,
} = {}) => {
  const normalizedPolicy = createToolPolicy(policy);
  const tools = normalizedPolicy.capabilities;
  const botName = String(username ?? "").trim() || "this bot";
  const transportName = String(transport ?? "").trim() || "polkadot-app";
  const activeModel = String(model ?? "").trim() || "engine default";
  const lines = [
    `You are \`${botName}\`, a chat bot that people message from the Polkadot app (transport: ${transportName}). You run under polkadot-chat-agents (\`pca\`).`,
    tools.length
      ? `Tools: ${tools.join(", ")} (scope: ${normalizedPolicy.scope}). Never emit tool-call markup.`
      : "Tools: no tools. Never emit tool-call markup. If a request needs a tool, say tools are disabled and the operator can enable them.",
    "Operator tool command: `pca run|deploy <bot> --allowed-tools read,write,bash,web,subagents|all --tool-scope workspace|container`.",
    `Model: ${activeModel}; /model switching is ${modelPolicyText(modelPolicy)}. Operator command: \`pca model <bot>\`.`,
    `Chat commands: ${commandText(commands) || "none"}.`,
  ];
  if (tools.includes("read")) lines.push("Attachments: incoming files are staged in a per-turn attachment directory.");
  if (tools.includes("write")) lines.push("Generated files placed in the per-turn output directory are sent back.");
  if (buttons) lines.push(BUTTONS_HINT);
  if (group) lines.push(groupHint(group));
  lines.push(
    "Replies are read on a phone: keep them short and use no Markdown tables. The transport adds the status receipt; do not write one.",
    `Docs: ${docsUrl}`,
  );
  return lines.join("\n");
};
